version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./employee_app.db
      - SECRET_KEY=EEEeNwdjOmiTzu75ghqMCGbVxsu-yA3QvFChNJDMDe0
    volumes:
      - .:/app
      - /app/__pycache__
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload