"""remove phone_number from employee

Revision ID: 1bfa302583d9
Revises: 3afd608228ca
Create Date: 2026-01-13 11:37:19.884956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfa302583d9'
down_revision: Union[str, Sequence[str], None] = '3afd608228ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('phone_number', sa.VARCHAR(length=15), nullable=True))
    # ### end Alembic commands ###
