"""Add phone_number to employee

Revision ID: f84e6399ddce
Revises: bdeb05b7a645
Create Date: 2026-01-12 10:21:13.996654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84e6399ddce'
down_revision: Union[str, Sequence[str], None] = 'bdeb05b7a645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.add_column('employees', sa.Column('phone_number', sa.String(length=15), nullable=True))
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.add_column('messages', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'timestamp')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.drop_column('employees', 'phone_number')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    # ### end Alembic commands ###
